# Generated by Django 5.1.2 on 2024-10-20 11:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eesnimi', models.CharField(blank=True, max_length=150, null=True)),
                ('perekonnanimi', models.CharField(blank=True, max_length=150, null=True)),
                ('firma_nimi', models.CharField(blank=True, max_length=255, null=True)),
                ('klient_tüüp', models.CharField(choices=[('Eraisik', 'Eraisik'), ('Juriidiline isik', 'Juriidiline isik'), ('Munitsipaal', 'Munitsipaal'), ('Välismaalane', 'Välismaalane')], max_length=100)),
                ('isikukood', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('loomise_kuupäev', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Linn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=100)),
                ('loomise_kuupäev', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Maakond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(max_length=100)),
                ('loomise_kuupäev', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Kinnisvara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadress', models.CharField(max_length=255)),
                ('tüüp', models.CharField(choices=[('Korter', 'Korter'), ('Maja', 'Maja'), ('Äripind', 'Äripind')], max_length=50)),
                ('ehitise_tüüp', models.CharField(choices=[('Kivimaja', 'Kivimaja'), ('Puumaja', 'Puumaja'), ('Paneelmaja', 'Paneelmaja')], max_length=50)),
                ('seisukord', models.CharField(choices=[('Elamiskõlbmatu', 'Elamiskõlbmatu'), ('Vajab remonti', 'Vajab remonti'), ('Keskmine', 'keskmine'), ('remonditud', 'remonditud'), ('Renoveeritud', 'Renoveeritud'), ('Uus', 'Uus')], max_length=50)),
                ('pindala', models.FloatField()),
                ('tube', models.IntegerField()),
                ('korrus', models.IntegerField()),
                ('ehitusaasta', models.IntegerField()),
                ('omandi_vorm', models.CharField(choices=[('Eraomand', 'Eraomand'), ('Korteriomand', 'Korteriomand')], max_length=50)),
                ('kirjeldus', models.TextField()),
                ('loomise_kuupäev', models.DateTimeField(default=django.utils.timezone.now)),
                ('linn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistics_app.linn')),
            ],
        ),
        migrations.CreateModel(
            name='Maakler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eesnimi', models.CharField(max_length=100)),
                ('perekonnanimi', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('büroo_nimi', models.CharField(max_length=255)),
                ('loomise_kuupäev', models.DateTimeField(default=django.utils.timezone.now)),
                ('maakond', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistics_app.maakond')),
            ],
        ),
        migrations.AddField(
            model_name='linn',
            name='maakond',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistics_app.maakond'),
        ),
        migrations.CreateModel(
            name='Tehing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tehingu_tüüp', models.CharField(choices=[('Müük', 'Müük'), ('Üür', 'Üür')], max_length=20)),
                ('kuupäev', models.DateField()),
                ('hind', models.IntegerField()),
                ('ruutmeetrihind', models.FloatField()),
                ('olek', models.CharField(choices=[('Kinnitatud', 'Kinnitatud'), ('Ootel', 'Ootel')], max_length=20)),
                ('loomise_kuupäev', models.DateTimeField(default=django.utils.timezone.now)),
                ('kinnisvara', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistics_app.kinnisvara')),
                ('maakler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='statistics_app.maakler')),
                ('müüjad', models.ManyToManyField(related_name='müüja_tehingud', to='statistics_app.klient')),
                ('ostjad', models.ManyToManyField(related_name='ostja_tehingud', to='statistics_app.klient')),
            ],
        ),
    ]
